version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  adminer:
    driver: ${VOLUMES_DRIVER}
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

  app:
    build:
      context: ./
      dockerfile: docker/app/app.Dockerfile
    working_dir: /var/www
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    volumes:
      - ./:/var/www
    networks:
      - backend

  web:
    build:
      context: ./
      dockerfile: docker/web/web.Dockerfile
    volumes:
      - ./public:/var/www/public
    ports:
      - ${WEB_PORT}:80
    networks:
      frontend:
      backend:
        aliases:
          - lv-playingpoker.localhost
    depends_on:
      - app

  db:
    build:
      context: ./
      dockerfile: docker/db/db.Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${DB_DATA_VOLUME}:/var/lib/mysql
    networks:
      - backend

  adminer:
    build:
      context: ./
      dockerfile: docker/adminer/adminer.Dockerfile
    ports:
      - "${ADMINER_PORT}:8080"
    volumes:
      - adminer:/sessions
    depends_on:
      - db
    networks:
      - frontend
      - backend

  redis:
    build:
      context: ./
      dockerfile: docker/redis/redis.Dockerfile
    networks:
      - backend

  echo-server:
    build:
      context: ./
      dockerfile: docker/echo-server/echo-server.Dockerfile
    depends_on:
      - redis
    ports:
      - "${ECHO_SERVER_PORT}:6001"
    networks:
      - frontend
      - backend

  queue:
    build:
      context: ./
      dockerfile: docker/queue/queue.Dockerfile
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    depends_on:
      - redis
    volumes:
      - ./:/var/www
      - ./docker/queue/supervisord.d:/etc/supervisord.d
    networks:
      - backend

  node:
    build:
      context: ./
      dockerfile: docker/node/node.Dockerfile
    tty: true
    volumes:
      - ./:/var/www

