version: '3.7'

services:

  app:
    env_file:
      - .envs/app.env
      - .envs/php-ini.env

  queue:
    env_file:
      - .envs/app.env
      - .envs/php-ini.env

  cron:
    env_file:
      - .envs/app.env
      - .envs/php-ini.env

  web:
    env_file:
      - .envs/web.env
    ports:
      - ${WEB_HTTP_PUBLISH_PORT}:80
      - ${WEB_HTTPS_PUBLISH_PORT}:443

  redis:
    env_file:
      - .envs/redis.env
    sysctls:
      net.core.somaxconn: "512"

  minio:
    env_file:
      - .envs/minio.env
