version: '3.7'

volumes:
  adminer:
    driver: ${VOLUMES_DRIVER}
  node_modules:
    driver: ${VOLUMES_DRIVER}

services:

  web-app:
    ports:
      - ${WEB_HTTP_PUBLISH_PORT}:80
      - ${WEB_HTTPS_PUBLISH_PORT}:443
    volumes:
      - ${DOCKER_VOLUME_ROOT_DIR}:/var/www/html

  adminer:
    volumes:
      - adminer:/sessions

  redis:
    ports:
      - "${REDIS_PUBLISH_PORT}:6379"

  queue:
    volumes:
      - ${DOCKER_VOLUME_ROOT_DIR}:/var/www/html
      - ./docker/queue/supervisord.d:/etc/supervisord.d

  node:
    volumes:
      - ${DOCKER_VOLUME_ROOT_DIR}:/var/www/html
      - node_modules:/var/www/html/node_modules